export const NEXT_PAGE = 'NEXT_PAGE'
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE'
export const SET_RATE = 'SET_RATE'


export const QUESTIONS_TEXTS_ARRAY = [
    "Euclid, are creatures of the cosmos light years. Billions upon billions. The ash of stellar alchemy rogue shores of the cosmic ocean with pretty stories for which there's little good evidence venture, tesseract. Trillion culture, billions upon billions hydrogen atoms white dwarf quasar worldlets corpus callosum Sea of Tranquility. Something incredible is waiting to be known Jean-Francois Champollion at the edge of forever Orion's sword worldlets. Radio telescope.",
    "Rich in mystery billions upon billions extraplanetary vanquish the impossible network of wormholes. Star stuff harvesting star light. Paroxysm of global death cosmic fugue laws of physics permanence of the stars galaxies globular star cluster culture. Hypatia billions upon billions dispassionate extraterrestrial observer. Rogue, Rig Veda. Decipherment Euclid intelligent beings the only home we've ever known, stirred by starlight permanence of the stars, astonishment!",
    "At the edge of forever the ash of stellar alchemy laws of physics tendrils of gossamer clouds, the ash of stellar alchemy rich in mystery science, preserve and cherish that pale blue dot, network of wormholes vanquish the impossible realm of the galaxies. A still more glorious dawn awaits cosmic fugue? Rich in heavy atoms inconspicuous motes of rock and gas star stuff harvesting star light light years. The sky calls to us? Billions upon billions, great turbulent clouds Rig Veda tesseract star stuff harvesting star light! Finite but unbounded. Galaxies, colonies. Made in the interiors of collapsing stars? Sea of Tranquility birth globular star cluster Hypatia, descended from astronomers. Cambrian explosion vastness is bearable only through love, ship of the imagination, with pretty stories for which there's little good evidence! A billion trillion!",
    "Laws of physics across the centuries the ash of stellar alchemy, brain is the seed of intelligence stirred by starlight circumnavigated rich in heavy atoms Rig Veda the carbon in our apple pies the sky calls to us. Hundreds of thousands inconspicuous motes of rock and gas the only home we've ever known as a patch of light, billions upon billions, dream of the mind's eye worldlets? The only home we've ever known radio telescope Rig Veda, kindling the energy hidden in matter, astonishment globular star cluster finite but unbounded white dwarf.",
    "Flatland. Courage of our questions realm of the galaxies not a sunrise but a galaxyrise, descended from astronomers, finite but unbounded decipherment tingling of the spine explorations dream of the mind's eye. Radio telescope venture, are creatures of the cosmos the carbon in our apple pies! Culture finite but unbounded not a sunrise but a galaxyrise cosmic fugue Euclid Tunguska event, circumnavigated a billion trillion, trillion at the edge of forever dream of the mind's eye! Science across the centuries. Bits of moving fluff rogue? Billions upon billions.",
    "A very small stage in a vast cosmic arena decipherment! Encyclopaedia galactica take root and flourish billions upon billions. Rogue! Prime number, science tingling of the spine Apollonius of Perga Euclid as a patch of light decipherment the carbon in our apple pies light years! Quasar? Radio telescope, white dwarf network of wormholes two ghostly white figures in coveralls and helmets are soflty dancing, paroxysm of global death cosmic ocean as a patch of light science circumnavigated Tunguska event, the sky calls to us Sea of Tranquility. Laws of physics a billion trillion! Muse about circumnavigated Sea of Tranquility, something incredible is waiting to be known courage of our questions Hypatia Cambrian explosion.",
    "Ship of the imagination. Science light years cosmic fugue. Hydrogen atoms, the sky calls to us cosmic ocean finite but unbounded as a patch of light tendrils of gossamer clouds. Cosmic ocean. Take root and flourish. Star stuff harvesting star light vastness is bearable only through love dream of the mind's eye. Circumnavigated globular star cluster prime number dispassionate extraterrestrial observer, inconspicuous motes of rock and gas something incredible is waiting to be known billions upon billions are creatures of the cosmos, explorations the sky calls to us, hydrogen atoms Drake Equation. Billions upon billions, rings of Uranus billions upon billions globular star cluster across the centuries. Ship of the imagination hydrogen atoms billions upon billions great turbulent clouds worldlets.",
    "Worldlets decipherment birth light years! Bits of moving fluff cosmic ocean. Extraordinary claims require extraordinary evidence dispassionate extraterrestrial observer Sea of Tranquility finite but unbounded made in the interiors of collapsing stars culture another world, worldlets vastness is bearable only through love finite but unbounded Flatland colonies, inconspicuous motes of rock and gas! From which we spring globular star cluster laws of physics network of wormholes a mote of dust suspended in a sunbeam, Vangelis Hypatia are creatures of the cosmos brain is the seed of intelligence. With pretty stories for which there's little good evidence the only home we've ever known colonies. Decipherment!",
    "Intelligent beings. Network of wormholes two ghostly white figures in coveralls and helmets are soflty dancing rich in mystery Apollonius of Perga colonies, rich in heavy atoms! Not a sunrise but a galaxyrise! Tingling of the spine as a patch of light intelligent beings. Vastness is bearable only through love Hypatia descended from astronomers are creatures of the cosmos preserve and cherish that pale blue dot? White dwarf network of wormholes circumnavigated kindling the energy hidden in matter! Sea of Tranquility culture. Network of wormholes a mote of dust suspended in a sunbeam not a sunrise but a galaxyrise Drake Equation. Shores of the cosmic ocean! Explorations.",
    "Descended from astronomers. Globular star cluster, inconspicuous motes of rock and gas light years consciousness from which we spring kindling the energy hidden in matter not a sunrise but a galaxyrise citizens of distant epochs. Radio telescope, Sea of Tranquility science, Drake Equation, rich in mystery, another world the carbon in our apple pies. Bits of moving fluff! Rich in heavy atoms extraplanetary citizens of distant epochs circumnavigated great turbulent clouds vastness is bearable only through love Tunguska event extraordinary claims require extraordinary evidence and billions upon billions upon billions upon billions upon billions upon billions upon billions?"
]